### ISSUE TITLE
Usability. Some hardresolvable cases while road building.

### ISSUE THREAD

**Issue by Ygarr** [Montandalar/advtrains#10]
And suggest ways how to avoid it?
1. Cannot to merge or connect in this node
![screenshot_20211115_114441](https://user-images.githubusercontent.com/14309871/141763465-dd6748cd-4692-4fb9-8e7d-92bfdb6e1f90.png)
![screenshot_20211115_114427](https://user-images.githubusercontent.com/14309871/141763708-17e67760-0b73-476d-8fe6-63aeb9395fba.png)
![screenshot_20211115_114008](https://user-images.githubusercontent.com/14309871/141764015-175a9007-ebd0-467e-884c-562d6c734561.png)
2.(Most important) Destroying mostly under railway! Not railway itself
"+" on the railway, but selected block under railway

![screenshot_20211115_113732](https://user-images.githubusercontent.com/14309871/141764277-a5ef6c73-6beb-4c34-b5df-d6e1d1fe5f1d.png)

**Comment by Montandalar** [comment]
1.For your first and second screenshots, it looks like your curvature is too sharp from one side. Then it is simple if you use a 90+Angle Diamond Crossing Track:
![Solution1a](https://user-images.githubusercontent.com/13659694/141772694-566a57fa-a66c-4d44-9edb-00e1dfce0442.jpeg)

For the third screenshot, I can't tell what you are trying to achieve. I hope this is the same problem, which I have already given the solution for. If not, also try the 90+Angle Diamond Crossing Track. See [the documentation on the trackworker](http://advtrains.de/wiki/doku.php?id=usage:tools:start#trackworker).

2. I think this can be solved with bigger node selection boxes. I'll get back to you on this.

**Comment by Montandalar** [comment]
Please test the branch [track_selectionboxes](https://github.com/Montandalar/advtrains/tree/track_selectionboxes) where I made the selection boxes on all the track nodes much bigger. This includes all straights, curves, turnouts (including 3-way and Y) and diamond crossings. I have tested them myself and in most cases it seems not to interfere too much but I need a second opinion.

I will be submitting this branch to the [developer mailing list](https://lists.sr.ht/~gpcf/advtrains-devel) as well.

**Comment by Ygarr** [comment]
(I readd mod whole from github)
Seems all the same but percent of false/incorrect settings is less. Subjectively 

![screenshot_20211117_133215](https://user-images.githubusercontent.com/14309871/142194268-3dcf1578-41b4-442f-80d9-bf3ed53a30bd.png)

destroying objects is also easier, but there are still rare(statistically :) rare ) misses 

![screenshot_20211117_132711](https://user-images.githubusercontent.com/14309871/142194329-8fbad11d-6d13-409d-851c-00a203b8add6.png)

**Comment by Montandalar** [comment]
Hmm it does not look like you have installed my branch correctly. This change was not done on master. Here is a [direct link](https://github.com/Montandalar/advtrains/archive/refs/heads/track_selectionboxes.zip). You may also find [this tutorial](https://www.cloudsavvyit.com/14700/how-to-clone-or-download-a-specific-branch-from-github/) helpful.

The selection box is much bigger than in your screenshot. See this video:

https://user-images.githubusercontent.com/13659694/142199690-a07f8517-184d-4c6e-8e13-1bf68792f845.mp4

**Comment by Ygarr** [comment]
Oh, definitely, the differences are clearly visible now. Hopefully this improvement will be in the mainstream. thankS
![screenshot_20211117_235049](https://user-images.githubusercontent.com/14309871/142288147-a551a9e2-1476-434e-841d-8505966494ba.png)

**Comment by Montandalar** [comment]
Was merged into master in 793210f7c216302d4970ebe52c2975c542f8f193
