### ISSUE TITLE
Slopes and road forks

### ISSUE THREAD

**Issue by Ygarr** [Montandalar/advtrains#11]
Unable get over the slopes. It's the same with the forks.
![screenshot_20211123_192513](https://user-images.githubusercontent.com/14309871/143076394-2b2e2263-f40c-4726-b254-0bad764c65ee.png)

**Comment by Montandalar** [comment]
Hi, I hope this useful illustration will help you. In particular you haven't address point 4: No nodes are allowed beside the slope nodes.

![SpaceRequirementsForAdvtrains](https://user-images.githubusercontent.com/13659694/143167357-86eb1470-5663-437e-ac49-bd7b8efe3195.png)

The solution to your particular case is to remove nodes beside your slope node like so:

![TrackSlopes_Ygarr](https://user-images.githubusercontent.com/13659694/143168253-4b1c57f1-33cd-4962-b4dd-fc3e27d8f411.png)
