### ISSUE TITLE
Setting route changes turnout to corner

### ISSUE THREAD

**Issue by Maverick2797** [Montandalar/advtrains#6]
Just updated to 487ca4e, setting the crossover route from the signal on the right seems to change the turnout to a corner instead of changing the turnout state. Changing it back to a turnout manually seems to work ok until the route is set again
![screenshot_20200912_215128](https://user-images.githubusercontent.com/49946595/92997002-63d87c00-f542-11ea-86f8-94ecbee81d99.png)

**Comment by gpcf** [comment]
Bug confirmed

**Comment by gpcf** [comment]
https://git.bananach.space/advtrains.git/commit/?id=1d224d6b4c714ff63f98d3f935ccbd9f697fb1d9

Here it is

**Comment by gpcf** [comment]
switchalt = "swlcr" on the standard switch, totally different from the switch state

**Comment by Montandalar** [comment]
Addressed by 61009bf and upstream by  1a743c2dd
